services:
  # ----------------------------------------
  # SERVICIO 1: BASE DE DATOS POSTGRESQL
  # ----------------------------------------
  db:
    image: postgres:16-alpine
    container_name: pawsity-db
    restart: unless-stopped
    # 1. CONEXIÓN CON TU ARCHIVO DE VARIABLES DE ENTORNO
    env_file:
      - docker.env
    # 2. INYECCIÓN SEGURA DE VARIABLES
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pawsity_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pawsity} -d ${POSTGRES_DB:-pawsity}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------
  # SERVICIO 2: ADMINER (Gestor Web de BD)
  # ----------------------------------------
  adminer:
    image: adminer:latest
    container_name: pawsity-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pawsity_pgdata: